// flow-typed signature: 0600eded5defa2895d091b5bc534122f
// flow-typed version: <<STUB>>/babel-preset-es2015-node4_v^2.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015-node4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015-node4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-es2015-node4/index' {
  declare module.exports: $Exports<'babel-preset-es2015-node4'>;
}
declare module 'babel-preset-es2015-node4/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015-node4'>;
}
