// flow-typed signature: 7ff3325af1f5ae906415a1ef371fd029
// flow-typed version: <<STUB>>/eslint-config-simenb-flow_v^8.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-simenb-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-simenb-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-simenb-flow/index' {
  declare module.exports: $Exports<'eslint-config-simenb-flow'>;
}
declare module 'eslint-config-simenb-flow/index.js' {
  declare module.exports: $Exports<'eslint-config-simenb-flow'>;
}
