// flow-typed signature: d99f661f8d259c2c26b7a196710289d1
// flow-typed version: <<STUB>>/licensor_v^3.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'licensor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'licensor' {
  declare module.exports: any;
}
